#!/usr/bin/env bash

get_selection() {
    # get a region of the screen for future screenshotting.
    # fix coordinates scale (for some reason, for me 150% is 1.3333 in slop and 2.0 in slurp)
    local -r scale="1.0"
    slurp -f "%w:%h:%x:%y" | perl -pe "s/(\d+)/\$1*$scale/ge"
    # slop -f "%w:%h:%x:%y"  | perl -pe "s/(\d+)/\$1*$scale/ge"
}

take_screenshot_region() {
    # function to take a screenshot of a given screen region.
    # $1 is the geometry of the region from get_selection().
    # $2 is the output file name.
    local -r geom="$1"
    local -r path="$2"
    # take full screenshot because spectacle doesn't support taking region via cli and crop it
    spectacle -nbo /proc/self/fd/1 | ffmpeg -loglevel error -i - -vf crop="$geom" -update true -vframes 1 -y "$path"
}

take_screenshot_window() {
    # function to take a screenshot of the current window.
    # $1 is the output file name.
    local -r path="$1"
    spectacle -nbaeo "$path"
}

copied_text() {
    # get the contents of the clipboard.
    wl-paste
}
